server:
  servlet:
    encoding:
      force-response: true #한글 깨짐 오류 해결
spring:
  datasource:
    url: jdbc:mysql://ec2-35-73-226-27.ap-northeast-1.compute.amazonaws.com/inkyu-db?&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    database: mysql

logging:
  level:
    org.hibernate.sql: debug

jwt:
  token:
    secret: hello
