server:
  servlet:
    encoding:
      force-response: true #한글 깨짐 오류 해결
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/inkyu-db?&rewriteBatchedStatements=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL55Dialect
#    database: mysql

logging:
  level:
    org.hibernate.sql: debug

jwt:
  token:
    secret: hello
